# Generated by Django 5.2.2 on 2025-06-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
                ('total_spots', models.IntegerField(default=0)),
                ('available_spots', models.IntegerField(default=0)),
                ('hourly_rate', models.IntegerField(default=0)),
                ('daily_rate', models.IntegerField(default=0)),
                ('monthly_rate', models.IntegerField(default=0)),
            ],
        ),
    ]
